### ISSUE TITLE
Consider removing the supports.interactivity = true

### ISSUE THREAD

**Issue by colorful-tones** [ockham/like-button#2]
> Remove Interactivity API dependency; now works without the Gutenberg plugin present.

Based on the [`v0.5.0` release](https://github.com/ockham/like-button/releases/tag/v0.5.0), it might be suitable to remove the `"interactivity": true` from the `block.json`

**Comment by ockham** [comment]
Thank you! Done in https://github.com/ockham/like-button/commit/4f1f895156d4352354ac3547032abd5d35cb55fe 😊
